### ISSUE TITLE
Is this usable on Windows with Python installed?

### ISSUE THREAD

**Issue by wandering-andy** [josecols/python-tidy#1]
I have Python installed and I've used it for other things but I don't see any way in your code to point the extension to my Python folder. Thanks!

**Comment by josecols** [comment]
The extension uses the directory of the current document you are working on, you don't need to make the reference yourself. 

However, if you want to see where is this in the code look at the function `tidy`. In this line `cmd = 'python "' + tidyPath + '" "' + file + '"';` the command to format the code is defined (file is the directory of your current document).

If you can't format the code it could be a NodeJS related problem, make sure you have it installed.
